### ISSUE TITLE
Missing clock result

### ISSUE THREAD

**Issue by szepeviktor** [mnot/httplint#56]
![image](https://github.com/mnot/redbot/assets/952007/b0c0e02b-0a7e-448b-994a-3ab2bc87a0f3)

https://redbot.org/?uri=https://www.futureweb.at/de/kontakt/team/

I cannot figure out why clock info is not displayed here.

> The server's clock is correct.

Please help me.

**Comment by mnot** [comment]
Based on what I see with the current resource, the caching tests are terminating before they get to this test because it contains `Cache-Control: no-store`. I'll rework things.

**Comment by szepeviktor** [comment]
Thank you.
